[package]
name = "exoneum"
version = "0.1.0"
authors = ["Roger Wilco <roger.wilco@protonmail.com>"]
homepage = "https://rogerwilcos.github.io"
repository = "https://github.com/rogerwilcos/exoneum"
readme = "README.md"
license = ""
publish = false

[dependencies]
